/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"
#include "USART.hpp"


USART serial;
DMA serial_dma;

int main(void)
{

	serial.Config.Port = USART1;
	serial.Config.USART_DMA = serial_dma;
    serial_dma.Config.Controller = DMA2;
    serial_dma.Config.Stream = DMA2_Stream7;
    serial_dma.Config.channel = 4;
    serial_dma.Config.circular_buffer = DISABLE;
    serial_dma.Config.direction = DMA::Direction::Memory_to_Peripheral;
    serial_dma.Config.flow_controller = DMA::Flow_Controller::DMA_Flow_Controller;
    serial_dma.Config.memory_data_size = DMA::Data_Size::bit8;
    serial_dma.Config.periphera_data_size = DMA::Data_Size::bit8;
    serial_dma.Config.priority = DMA::Priority::very_high;
    serial.Init();





    /* Loop forever */
	for(;;);
}
